services:
    php:
        build: './docker/php'
        user: ${UID:-1000}:${GID:-1000}
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
        command: php -S 0.0.0.0:80 -t ./public
    db:
        image: mariadb:10
        ports:
            - "3306:3306"
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: database
            MARIADB_USER: user
            MARIADB_PASSWORD: password
        volumes:
            - db-data:/var/lib/mysql
    node:
        image: node:20-alpine
        volumes:
            - .:/app
        working_dir: /app
        command: npm run watch

    adminer:
        image: adminer
        ports:
            - "8081:8080"
        depends_on:
            - db
volumes:
    db-data:
